version: '3.8'

services:

  kafka1:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka1
    hostname: kafka1
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "7071:7071"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://${HOST_IP:-127.0.0.1}:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CLUSTER_ID: "f7lZDNZPRnqe1wa1PkUf8w"   # generate once
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OPTS: "-javaagent:/opt/jmx_exporter.jar=7071:/opt/kafka-jmx.yml"
    volumes:
      - ./jmx_prometheus_javaagent-0.20.0.jar:/opt/jmx_exporter.jar
      - ./kafka-jmx.yml:/opt/kafka-jmx.yml
      - kafka1-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "KAFKA_OPTS='' kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  kafka2:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka2
    hostname: kafka2
    restart: unless-stopped
    ports:
      - "9093:9092"
      - "7072:7071"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29092,EXTERNAL://${HOST_IP:-127.0.0.1}:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CLUSTER_ID: "f7lZDNZPRnqe1wa1PkUf8w"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OPTS: "-javaagent:/opt/jmx_exporter.jar=7071:/opt/kafka-jmx.yml"
    volumes:
      - ./jmx_prometheus_javaagent-0.20.0.jar:/opt/jmx_exporter.jar
      - ./kafka-jmx.yml:/opt/kafka-jmx.yml
      - kafka2-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "KAFKA_OPTS='' kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  kafka3:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka3
    hostname: kafka3
    restart: unless-stopped
    ports:
      - "9094:9092"
      - "7073:7071"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:29092,EXTERNAL://${HOST_IP:-127.0.0.1}:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CLUSTER_ID: "f7lZDNZPRnqe1wa1PkUf8w"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OPTS: "-javaagent:/opt/jmx_exporter.jar=7071:/opt/kafka-jmx.yml"
    volumes:
      - ./jmx_prometheus_javaagent-0.20.0.jar:/opt/jmx_exporter.jar
      - ./kafka-jmx.yml:/opt/kafka-jmx.yml
      - kafka3-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "KAFKA_OPTS='' kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  kafka4:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka4
    hostname: kafka4
    restart: unless-stopped
    ports:
      - "9095:9092"
      - "7074:7071"
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka4:29092,EXTERNAL://${HOST_IP:-127.0.0.1}:9095
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CLUSTER_ID: "f7lZDNZPRnqe1wa1PkUf8w"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OPTS: "-javaagent:/opt/jmx_exporter.jar=7071:/opt/kafka-jmx.yml"
    volumes:
      - ./jmx_prometheus_javaagent-0.20.0.jar:/opt/jmx_exporter.jar
      - ./kafka-jmx.yml:/opt/kafka-jmx.yml
      - kafka4-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "KAFKA_OPTS='' kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      kafka4:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092,kafka2:29092,kafka3:29092,kafka4:29092


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      kafka4:
        condition: service_healthy


  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      prometheus:
        condition: service_started


volumes:
  grafana-data:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  kafka4-data:
